---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/cluster-config/openshift-pipelines-operator/overlays/latest
    repoURL: https://github.com/tosin2013/sno-quickstarts.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
